### ISSUE TITLE
这是一个很优秀的项目，如果能支持回退功能就好了。

### ISSUE THREAD

**Issue by Furinazzz** [3011/poe-telegram-bot#1]
这是一个很优秀的项目，感谢大佬的付出。如果能支持回退功能就好了。
比如输入/back可以回退上一轮对话，类似于撤回功能吧。

**Comment by 3011** [comment]
你好，应该可以实现 Poe 官方网页的 "Stop停止回复" 功能，不过该次对话仍会存在于上下文中，会影响bot的后续回复，并不是撤回功能，撤回功能应该暂时无法实现。

**Comment by Shirasawaz** [comment]
感谢大佬回复🥰，可以参考一下chatgpt-mirai-qq-bot的源代码实现 https://github.com/lss233/chatgpt-mirai-qq-bot/blob/browser-version/adapter/quora/poe.py

**Comment by 3011** [comment]
> 感谢大佬回复🥰，可以参考一下chatgpt-mirai-qq-bot的源代码实现 https://github.com/lss233/chatgpt-mirai-qq-bot/blob/browser-version/adapter/quora/poe.py

感谢支持，已新增该功能。

**Comment by Shirasawaz** [comment]
非常感谢！
